import assert from 'node:assert/strict';
import { mkdir, mkdtemp, writeFile } from 'node:fs/promises';
import { tmpdir } from 'node:os';
import path from 'node:path';
import test from 'node:test';
import { _electron, expect, type ElectronApplication } from '@playwright/test';
import type { HostState, TerminalInfo } from '../../packages/protocol/index';

const enabled=process.platform==='win32'&&process.env.MONGLE_E2E_COMPACT==='1';
test('compact desktop: native titlebar, persistent sidebar, live shell identity, narrow layout and themes', {skip:!enabled,timeout:120000},async()=>{
  const root=process.cwd(),output=path.join(root,'test-results/e2e/compact-workspace');
  await mkdir(output,{recursive:true});
  const parent=path.resolve(process.env.MONGLE_E2E_DATA_ROOT||tmpdir());await mkdir(parent,{recursive:true});
  const dataDir=await mkdtemp(path.join(parent,'mongle-compact-'));
  const env:NodeJS.ProcessEnv={...process.env,MONGLE_DATA_DIR:dataDir};delete env.ELECTRON_RUN_AS_NODE;
  let app:ElectronApplication|undefined;
  const errors:string[]=[],proof:Record<string,unknown>={passed:false,isolated:true};
  try{
    const packaged=process.env.MONGLE_E2E_EXE;
    app=await _electron.launch({executablePath:packaged||path.join(root,'node_modules/electron/dist/electron.exe'),args:packaged?[]:[root],cwd:root,env:env as Record<string,string>});
    proof.packaged=Boolean(packaged);
    const page=await app.firstWindow();page.setDefaultTimeout(15000);page.on('pageerror',error=>errors.push(error.message));
    await expect(page.getByRole('button',{name:'새 그룹',exact:true})).toBeEnabled({timeout:30000});
    await app.evaluate(({BrowserWindow})=>BrowserWindow.getAllWindows()[0].setContentSize(1440,900));
    const request=<T=any>(method:string,params?:unknown)=>page.evaluate(({method,params})=>window.mongle!.request<T>(method,params),{method,params});
    const state=()=>request<HostState>('state.get');
    const initial=await state(),group=initial.groups[0],cmd=initial.profiles.find(profile=>profile.kind==='cmd');assert.ok(cmd);
    await request('groups.update',{id:group.id,revision:group.revision,name:'몽글 프로젝트',cwd:'C:\\Windows',profileId:cmd.id});
    const first=await request<TerminalInfo>('terminals.create',{groupId:group.id,profileId:cmd.id});
    const second=await request<TerminalInfo>('terminals.create',{groupId:group.id,profileId:cmd.id,splitTarget:first.id,axis:'horizontal'});
    const third=await request<TerminalInfo>('terminals.create',{groupId:group.id,profileId:cmd.id,splitTarget:second.id,axis:'vertical'});
    for(const [terminal,title] of [[first,'workspace'],[second,'테스트'],[third,'작업 노트']] as const)await request('terminals.rename',{id:terminal.id,title});
    await request('groups.create',{name:'서버',cwd:'C:\\Windows',profileId:cmd.id});
    await expect(page.locator('.pane:visible')).toHaveCount(3);
    await expect(page.getByText('여기서 제어 중',{exact:true})).toHaveCount(3);
    const pane=page.locator(`.pane[data-terminal-id="${first.id}"]`);
    await pane.locator('.xterm-helper-textarea').focus();await page.keyboard.type('set MONGLE_COMPACT_PROOF=SESSION_OK');await page.keyboard.press('Enter');
    await expect(pane.locator('.xterm-rows')).toContainText('MONGLE_COMPACT_PROOF');
    const before=await state(),identity=(value:HostState)=>value.terminals.map(({id,pid,generation})=>({id,pid,generation}));
    await page.evaluate(()=>{(window as any).__compactNodes=Array.from(document.querySelectorAll('.pane .xterm'));});
    const open=await pane.boundingBox();assert.ok(open);
    await page.screenshot({path:path.join(output,'01-expanded.png')});
    assert.equal(await page.evaluate(()=>window.mongle!.titleBarOverlay),true);
    const overlay=await page.evaluate(()=>{const overlay=(navigator as any).windowControlsOverlay,rect=overlay.getTitlebarAreaRect();return {visible:overlay.visible,x:rect.x,width:rect.width,height:rect.height};});
    assert.equal(overlay.visible,true);assert.ok(overlay.height>0);proof.overlay=overlay;
    const sidebar=page.getByRole('complementary',{name:'작업 탐색'});
    const toggleBefore=await sidebar.getByRole('button',{name:'사이드바 접기',exact:true}).locator('svg').boundingBox();assert.ok(toggleBefore);
    await sidebar.getByRole('button',{name:'사이드바 접기',exact:true}).click();
    await expect(page.getByRole('button',{name:'사이드바 펼치기',exact:true})).toHaveAttribute('aria-expanded','false');
    assert.deepEqual(await sidebar.getByRole('button',{name:'사이드바 펼치기',exact:true}).locator('svg').boundingBox(),toggleBefore);
    proof.sidebarToggle={x:toggleBefore.x,y:toggleBefore.y,fixedAcrossStates:true};
    assert.equal((await page.locator('.sidebar').boundingBox())!.width,44);
    assert.ok((await pane.boundingBox())!.width>open.width+60);
    await expect.poll(async()=>(await state()).terminals.find(terminal=>terminal.id===first.id)!.cols).toBeGreaterThan(before.terminals.find(terminal=>terminal.id===first.id)!.cols);
    const cells=(value:HostState)=>{const terminal=value.terminals.find(terminal=>terminal.id===first.id)!;return {cols:terminal.cols,rows:terminal.rows};};
    proof.geometry={expanded:cells(before),collapsed:cells(await state()),expandedSidebar:212,collapsedSidebar:44};
    assert.equal(await page.evaluate(()=>Array.from(document.querySelectorAll('.pane .xterm')).every((node,i)=>node===(window as any).__compactNodes[i])),true);
    assert.deepEqual(identity(await state()),identity(before));assert.deepEqual((await state()).groups[0].layout,before.groups[0].layout);
    await page.getByRole('button',{name:'파일 탐색기',exact:true}).click();await expect(page.locator('.file-explorer')).toBeVisible();
    await page.getByRole('button',{name:'파일 탐색기',exact:true}).click();await expect(page.locator('.file-explorer')).toHaveCount(0);
    await page.getByRole('button',{name:'설정',exact:true}).click();await expect(page.getByLabel('터미널 글자 크기',{exact:true})).toHaveValue('13');
    await page.getByRole('button',{name:'설정 닫기',exact:true}).click();
    await page.screenshot({path:path.join(output,'02-collapsed.png')});
    await page.reload();await expect(page.getByRole('button',{name:'사이드바 펼치기',exact:true})).toBeVisible();
    await expect(page.locator('.pane:visible')).toHaveCount(3);assert.equal((await page.locator('.sidebar').boundingBox())!.width,44);
    assert.deepEqual(identity(await state()),identity(before));
    await pane.locator('.xterm-helper-textarea').focus();await page.keyboard.type('echo %MONGLE_COMPACT_PROOF%');await page.keyboard.press('Enter');
    await expect(pane.locator('.xterm-rows')).toContainText('SESSION_OK');
    await page.getByRole('button',{name:'사이드바 펼치기',exact:true}).click();
    const resize=page.getByRole('separator',{name:'사이드바 너비',exact:true});await resize.focus();await page.keyboard.press('ArrowRight');
    const savedWidth=(await page.locator('.sidebar').boundingBox())!.width;assert.equal(savedWidth,222);
    await page.getByRole('button',{name:'설정',exact:true}).click();await page.getByLabel('터미널 글자 크기',{exact:true}).selectOption('16');
    await page.getByRole('button',{name:'밝게',exact:true}).click();await page.getByRole('button',{name:'설정 닫기',exact:true}).click();
    await page.reload();await expect(page.locator('.pane:visible')).toHaveCount(3);
    assert.equal((await page.locator('.sidebar').boundingBox())!.width,savedWidth);
    await page.getByRole('button',{name:'설정',exact:true}).click();await expect(page.getByLabel('터미널 글자 크기',{exact:true})).toHaveValue('16');
    await page.screenshot({path:path.join(output,'03-settings-light.png')});
    await page.getByRole('button',{name:'설정 닫기',exact:true}).click();
    await app.evaluate(({BrowserWindow})=>BrowserWindow.getAllWindows()[0].setContentSize(760,600));
    await page.getByRole('button',{name:'사이드바 접기',exact:true}).click();
    const toggle=await page.getByRole('button',{name:'사이드바 펼치기',exact:true}).boundingBox();assert.ok(toggle&&toggle.x+toggle.width<616);
    assert.equal(await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth),true);
    await page.getByRole('navigation',{name:'작업 공간 전환'}).getByRole('button',{name:'서버',exact:true}).click();
    await expect(page.getByRole('heading',{name:'터미널을 열어 시작하세요'})).toBeVisible();
    await page.getByRole('navigation',{name:'작업 공간 전환'}).getByRole('button',{name:'몽글 프로젝트',exact:true}).click();await expect(page.locator('.pane:visible')).toHaveCount(3);
    await page.screenshot({path:path.join(output,'04-narrow-light.png')});
    await app.evaluate(({BrowserWindow})=>BrowserWindow.getAllWindows()[0].maximize());
    assert.equal(await app.evaluate(({BrowserWindow})=>BrowserWindow.getAllWindows()[0].isMaximized()),true);
    await app.evaluate(({BrowserWindow})=>BrowserWindow.getAllWindows()[0].unmaximize());
    assert.deepEqual(identity(await state()),identity(before));assert.deepEqual(errors,[]);
    proof.passed=true;proof.savedWidth=savedWidth;proof.panes=before.terminals.length;proof.errors=errors;
  }finally{
    if(app){const page=await app.firstWindow().catch(()=>undefined);await page?.evaluate(()=>window.mongle!.request('host.shutdown')).catch(()=>{});await app.close().catch(()=>{});}
    await writeFile(path.join(output,'result.json'),JSON.stringify(proof,null,2));
  }
});
