import test from 'node:test';
import assert from 'node:assert/strict';
import { mkdtemp, mkdir, readFile, writeFile, rm, realpath } from 'node:fs/promises';
import { existsSync } from 'node:fs';
import { tmpdir } from 'node:os';
import path from 'node:path';
import { randomUUID } from 'node:crypto';
import { createServer } from 'node:http';
import { chromium, expect } from '@playwright/test';
import { HostCore } from '../../packages/host/core';
import type { ConnectionContext, TerminalInfo } from '../../packages/protocol';

test('shared explorer follows selected terminal and cwd, rejects late previews and preserves live panes', { skip: process.platform !== 'win32' || !existsSync('dist/web/index.html'), timeout: 60000 }, async t => {
  const root = await mkdtemp(path.join(tmpdir(), 'mongle-files-ui-'));
  const folderA = path.join(root, '프로젝트 A'), folderB = path.join(root, '프로젝트 B');
  await mkdir(path.join(folderA, 'src'), { recursive: true }); await mkdir(folderB);
  await writeFile(path.join(folderA, 'README.txt'), '<script>window.previewExecuted=true</script>\n한글 미리보기');
  await writeFile(path.join(folderA, 'slow.txt'), 'OLD_PREVIEW_MUST_NOT_APPEAR');
  await writeFile(path.join(folderA, 'src', 'nested.txt'), 'nested');
  await writeFile(path.join(folderB, 'second.txt'), '프로젝트 B 파일');
  const host = new HostCore({ dataDir: path.join(root, 'host'), name: '파일 탐색기 검증 PC' }); await host.init();
  t.after(async () => { await host.close(); await rm(root, { recursive: true, force: true }); });
  const ctx: ConnectionContext = { id: randomUUID(), deviceId: 'test-owner', deviceName: '테스트', owner: true }; host.connect(ctx, () => {});
  const groupId = host.getState().groups[0].id;
  const first: TerminalInfo = await host.handle('terminals.create', { groupId, cwd: folderA, profileId: 'cmd' }, ctx);
  const second: TerminalInfo = await host.handle('terminals.create', { groupId, cwd: folderB, profileId: 'cmd' }, ctx);
  await host.handle('terminals.rename', { id: first.id, title: '터미널 A' }, ctx);
  await host.handle('terminals.rename', { id: second.id, title: '터미널 B' }, ctx);
  const third: TerminalInfo = await host.handle('terminals.create', { groupId, cwd: folderA, profileId: 'cmd', splitTarget: first.id, axis: 'vertical' }, ctx);
  const fourth: TerminalInfo = await host.handle('terminals.create', { groupId, cwd: folderB, profileId: 'cmd', splitTarget: second.id, axis: 'vertical' }, ctx);
  await host.handle('terminals.rename', { id: third.id, title: '터미널 C' }, ctx);
  await host.handle('terminals.rename', { id: fourth.id, title: '터미널 D' }, ctx);
  const browser = await chromium.launch({ channel: 'chrome', headless: true });
  const page = await browser.newPage({ viewport: { width: 1440, height: 900 } });
  const errors: string[] = []; page.on('pageerror', error => errors.push(error.message));
  const requests: string[] = []; let releaseSlow: (() => void) | undefined; let copied = '';
  const server = createServer(async (req, res) => {
    try { const file = path.resolve('dist/web', (req.url === '/' ? '/index.html' : req.url!).slice(1)); if (!file.startsWith(path.resolve('dist/web') + path.sep)) throw new Error(); res.setHeader('Content-Type', file.endsWith('.js') ? 'application/javascript' : file.endsWith('.css') ? 'text/css' : 'text/html'); res.end(await readFile(file)); }
    catch { res.writeHead(404).end(); }
  });
  await new Promise<void>(resolve => server.listen(0, '127.0.0.1', resolve)); const address = server.address(); assert.ok(address && typeof address !== 'string');
  await page.exposeBinding('hostRequest', async (_source, method: string, params: any) => {
    requests.push(method); const result = await host.handle(method, params, ctx);
    if (method === 'files.open' && params.path === 'slow.txt') await new Promise<void>(resolve => { releaseSlow = resolve; });
    return result;
  });
  await page.exposeBinding('copyPath', (_source, value: string) => { copied = value; });
  host.disconnect(ctx.id);
  host.connect(ctx, event => { void page.evaluate(event => (window as any).__listeners?.forEach((listener: any) => listener(event)), event).catch(() => {}); });
  await page.addInitScript('window.__name = function(fn) { return fn; };');
  await page.addInitScript(({ connectionId }) => {
    const listeners = new Set(); (window as any).__listeners = listeners;
    (window as any).mongle = { request: (method: string, params: any) => (window as any).hostRequest(method, params), subscribe: (fn: any) => { listeners.add(fn); return () => listeners.delete(fn); }, onConnection: (fn: any) => { fn({ status: 'connected', owner: true, connectionId }); return () => {}; }, listHosts: async () => [{ id: 'local', name: '검증 PC', local: true, selected: true }], writeClipboard: (value: string) => (window as any).copyPath(value) };
  }, { connectionId: ctx.id });
  try {
    await page.goto(`http://127.0.0.1:${address.port}`);
    const paneA = page.locator(`[data-terminal-id="${first.id}"]`), paneB = page.locator(`[data-terminal-id="${second.id}"]`);
    await paneA.locator('textarea').focus();
    await page.getByRole('button', { name: '파일 탐색기', exact: true }).click();
    const explorer = page.getByRole('complementary', { name: '파일 탐색기' });
    const editor = page.getByRole('region', { name: '파일 편집기', exact: true });
    const content = editor.locator('.document-body:not([hidden]) .cm-content');
    await expect(explorer).toHaveCount(1);
    await expect(page.locator('.pane')).toHaveCount(4);
    await expect(explorer.locator('.file-terminal-name')).toHaveText('터미널 A');
    await explorer.getByRole('button', { name: 'src', exact: true }).click();
    await expect(explorer.getByRole('button', { name: 'nested.txt', exact: true })).toBeVisible();
    await explorer.getByRole('button', { name: 'README.txt', exact: true }).click();
    await expect(content).toContainText('한글 미리보기');
    assert.equal(await page.evaluate(() => (window as any).previewExecuted), undefined);
    const before = requests.length;
    await editor.getByRole('button', { name: '파일 경로 복사', exact: true }).click();
    assert.equal(await realpath(copied), await realpath(path.join(folderA, 'README.txt')));
    assert.ok(!requests.slice(before).some(method => method.startsWith('control.') || method === 'terminal.input'));
    await content.fill('한글 편집과 저장\n'); await content.press('Control+s');
    await expect.poll(() => readFile(path.join(folderA, 'README.txt'), 'utf8')).toBe('한글 편집과 저장\n');
    await content.fill('저장하지 않은 내 수정');
    await writeFile(path.join(folderA, 'README.txt'), '다른 프로그램의 변경');
    await editor.getByRole('button', { name: '파일 저장', exact: true }).click();
    await expect(editor.getByRole('alert')).toContainText('다른 프로그램');
    await expect(content).toHaveText('저장하지 않은 내 수정');
    assert.equal(await readFile(path.join(folderA, 'README.txt'), 'utf8'), '다른 프로그램의 변경');
    await editor.getByRole('button', { name: 'README.txt 닫기', exact: true }).click();
    await expect(page.getByRole('alertdialog')).toBeVisible();
    await page.getByRole('button', { name: '계속 편집', exact: true }).click();
    await expect(content).toHaveText('저장하지 않은 내 수정');
    await editor.getByRole('button', { name: '디스크 파일 다시 열기', exact: true }).first().click();
    await page.getByRole('button', { name: '변경 버리기', exact: true }).click();
    await expect(content).toHaveText('다른 프로그램의 변경');
    await explorer.getByRole('button', { name: 'slow.txt', exact: true }).click();
    await expect.poll(() => Boolean(releaseSlow)).toBe(true);
    await paneB.locator('textarea').focus();
    await expect(explorer.locator('.file-terminal-name')).toHaveText('터미널 B');
    await explorer.getByRole('button', { name: 'second.txt', exact: true }).click();
    await expect(content).toHaveText('프로젝트 B 파일');
    releaseSlow!();
    await expect(content).toHaveText('프로젝트 B 파일');
    await writeFile(path.join(folderB, 'new.txt'), 'new');
    await explorer.getByRole('button', { name: '새로고침', exact: true }).click();
    await expect(explorer.getByRole('button', { name: 'new.txt', exact: true })).toBeVisible();
    const separator = page.getByRole('separator', { name: '파일 작업 영역 너비' });
    await separator.focus(); await page.keyboard.press('ArrowLeft'); await expect(separator).toHaveAttribute('aria-valuenow', '740');
    await paneA.locator('textarea').focus();
    await expect(paneA.getByText('여기서 제어 중', { exact: true })).toBeVisible();
    await page.keyboard.insertText(`cd /d "${path.join(folderA, 'src')}"`); await page.keyboard.press('Enter');
    await expect.poll(async () => realpath(await explorer.locator('.file-root').innerText())).toBe(await realpath(path.join(folderA, 'src')));
    await expect(explorer.getByRole('button', { name: 'nested.txt', exact: true })).toBeVisible();
    await mkdir('test-results/file-explorer', { recursive: true });
    await explorer.getByRole('button', { name: 'nested.txt', exact: true }).click();
    await expect(content).toHaveText('nested');
    await page.screenshot({ path: 'test-results/file-explorer/dark.png' });
    await page.getByRole('button', { name: '설정', exact: true }).first().click();
    await page.getByRole('button', { name: '밝게', exact: true }).click(); await page.getByRole('button', { name: '설정 닫기' }).click();
    await page.screenshot({ path: 'test-results/file-explorer/light.png' });
    await explorer.getByRole('button', { name: '파일 탐색기 닫기' }).click(); await expect(explorer).toHaveCount(0);
    assert.equal(host.getState().terminals.find(info => info.id === first.id)?.pid, first.pid);
    assert.equal(host.getState().terminals.find(info => info.id === second.id)?.pid, second.pid);
    await page.getByRole('button', { name: '파일 탐색기', exact: true }).click(); await expect(explorer).toHaveCount(1);
    await page.setViewportSize({ width: 390, height: 844 });
    await expect(explorer).toBeVisible();
    assert.ok((await explorer.boundingBox())!.width <= 390);
    await page.screenshot({ path: 'test-results/file-explorer/mobile.png' });
    await explorer.getByRole('button', { name: '현재 폴더 경로 복사' }).focus();
    await page.keyboard.press('Escape'); await expect(explorer).toHaveCount(0);
    assert.deepEqual(errors, []);
  } finally { releaseSlow?.(); host.disconnect(ctx.id); await browser.close(); await new Promise<void>(resolve => server.close(() => resolve())); }
});
