import test from 'node:test';
import assert from 'node:assert/strict';
import { mkdir, readFile, rm, writeFile } from 'node:fs/promises';
import { existsSync } from 'node:fs';
import path from 'node:path';
import { tmpdir } from 'node:os';
import { randomUUID } from 'node:crypto';
import { createServer } from 'node:http';
import { chromium, expect } from '@playwright/test';
import { HostCore } from '../../packages/host/core';
import { git, gitFixture } from '../helpers/git';
import { leafIds, type ConnectionContext } from '../../packages/protocol';

test('worktree UI with real Git and shells: optional opening, focus, tabs, ownership, deletion and mobile', {skip:process.platform!=='win32'||!existsSync('dist/web/index.html'),timeout:120000},async t=>{
  const fixture=await gitFixture(),host=new HostCore({dataDir:fixture.data,name:'워크트리 검증 PC'});await host.init();
  t.after(async()=>{await host.close();assert.equal(path.dirname(fixture.root),tmpdir());assert.ok(path.basename(fixture.root).startsWith('mongle-git-'));await rm(fixture.root,{recursive:true,force:true});});
  const ctx:ConnectionContext={id:randomUUID(),deviceId:'worktree-ui',deviceName:'검증 화면',owner:true},remote:ConnectionContext={id:randomUUID(),deviceId:'other',deviceName:'다른 기기',owner:false};
  host.connect(ctx,()=>{});host.connect(remote,()=>{});
  const group=host.getState().groups[0];await host.handle('groups.update',{id:group.id,revision:group.revision,name:'워크트리 프로젝트',cwd:fixture.repository,profileId:'cmd'},ctx);
  const browser=await chromium.launch({channel:'chrome',headless:true});t.after(()=>browser.close());
  const page=await browser.newPage({viewport:{width:1440,height:900}});page.setDefaultTimeout(15000);
  const errors:string[]=[];page.on('pageerror',error=>errors.push(error.message));
  const server=createServer(async(req,res)=>{try{const file=path.resolve('dist/web',new URL(req.url||'/','http://localhost').pathname.slice(1)||'index.html');if(!file.startsWith(path.resolve('dist/web')+path.sep))throw new Error();res.setHeader('Content-Type',file.endsWith('.js')?'application/javascript':file.endsWith('.css')?'text/css':file.endsWith('.png')?'image/png':'text/html');res.end(await readFile(file));}catch{res.writeHead(404).end();}});
  await new Promise<void>(resolve=>server.listen(0,'127.0.0.1',resolve));t.after(()=>new Promise<void>(resolve=>server.close(()=>resolve())));const address=server.address();assert.ok(address&&typeof address!=='string');
  let delivery=Promise.resolve(),loseCreateResponse=false,delayedOpen:{entered:boolean;release:Promise<void>}|undefined;
  let activeReads=0,maxReads=0,measureReads=false;
  await page.exposeBinding('worktreeRequest',async(_source,method:string,params:unknown)=>{
    const read=method==='projects.inspect'||method==='worktrees.refresh';if(read){activeReads++;if(measureReads)maxReads=Math.max(maxReads,activeReads);}
    try{const result=await host.handle(method,params,ctx);await delivery;if(method==='worktrees.create'&&loseCreateResponse){loseCreateResponse=false;throw new Error('검증용 응답 유실');}if(method==='worktrees.open'&&delayedOpen){const gate=delayedOpen;gate.entered=true;await gate.release;delayedOpen=undefined;}return result;}finally{if(read)activeReads--;}
  });
  host.connect(ctx,event=>{delivery=delivery.then(()=>page.evaluate(value=>(window as any).__worktreeListeners?.forEach((fn:any)=>fn(value)),event)).catch(()=>{});});
  await page.addInitScript('window.__name=function(fn){return fn;};');
  await page.addInitScript(({connectionId})=>{const listeners=new Set();(window as any).__worktreeListeners=listeners;(window as any).mongle={request:(method:string,params:unknown)=>(window as any).worktreeRequest(method,params),subscribe:(fn:any)=>{listeners.add(fn);return()=>listeners.delete(fn);},onConnection:(fn:any)=>{fn({status:'connected',owner:true,connectionId});return()=>{};},listHosts:async()=>[{id:'local',name:'워크트리 검증 PC',local:true,selected:true}]};},{connectionId:ctx.id});
  const output=path.resolve('test-results/worktrees');await mkdir(output,{recursive:true});
  const pane=(id:string)=>page.locator(`[data-terminal-id="${id}"]`);
  const worktree=(name:string)=>host.getState().worktrees!.find(w=>w.name===name)!;
  const terminals=(id:string)=>host.getState().terminals.filter(t=>t.worktreeId===id);
  async function expectAnchoredMenu(name:string,placement:'below'|'above'='below'){
    const trigger=page.getByLabel(`${name}${name==='작업 프로젝트'?'':' 워크트리'} 메뉴`,{exact:true}),menu=page.getByRole('menu',{name:`${name}${name==='작업 프로젝트'?'':' 워크트리'} 작업`});
    await expect(menu).toBeVisible();await expect(trigger).toHaveAttribute('aria-expanded','true');
    await expect.poll(async()=>{
      const anchor=(await trigger.boundingBox())!,popup=(await menu.boundingBox())!,viewport=page.viewportSize()!;
      return Math.abs(popup.x+popup.width-anchor.x-anchor.width)<2 && popup.x>=8 && popup.x+popup.width<=viewport.width-8 && popup.y>=8 && popup.y+popup.height<=viewport.height-8 && Math.abs(placement==='below'?popup.y-anchor.y-anchor.height-4:anchor.y-popup.y-popup.height-4)<2;
    }).toBe(true);
    assert.equal(await menu.evaluate(element=>{const bounds=element.getBoundingClientRect();return element.contains(document.elementFromPoint(bounds.x+bounds.width/2,bounds.y+bounds.height-12));}),true,'menu must not be clipped or covered by the sidebar');
  }
  try{
    await page.goto(`http://127.0.0.1:${address.port}`);
    await page.getByRole('button',{name:'새 터미널',exact:true}).click();await page.getByRole('dialog').getByRole('button',{name:'터미널 열기',exact:true}).click();
    await expect.poll(()=>host.getState().terminals.length).toBe(1);
    const original=host.getState().terminals[0];await expect(pane(original.id)).toBeVisible();
    await expect(page.locator(`[data-sidebar-terminal-id="${original.id}"]`)).toBeVisible();
    await pane(original.id).getByRole('button',{name:'워크트리',exact:true}).click();await expect(page.getByLabel('대상 저장소')).toHaveText(fixture.repository.replaceAll('\\','/'));await page.getByRole('button',{name:'취소',exact:true}).click();
    await expect(page.getByRole('button',{name:'작업 프로젝트 열기'})).toBeVisible();
    await expect(page.locator(`[data-sidebar-terminal-id="${original.id}"]`)).toHaveCount(0);
    await expect(page.locator('[data-worktree-kind=main] .worktree-kind')).toHaveText('기본');
    await expect(page.locator('[data-worktree-kind=main] .lucide-git-branch')).toHaveCount(0);
    await expect(page.locator('.sidebar').getByRole('button',{name:'워크트리',exact:true})).toHaveCount(0);
    await page.getByLabel('작업 프로젝트 메뉴').click();await expectAnchoredMenu('작업 프로젝트');
    await expect(page.getByRole('menuitem')).toHaveCount(2);await expect(page.getByRole('menuitem',{name:'이름 변경',exact:true})).toBeFocused();
    await page.keyboard.press('End');await expect(page.getByRole('menuitem',{name:'목록 새로고침'})).toBeFocused();
    await page.keyboard.press('Escape');await expect(page.getByRole('menu')).toHaveCount(0);await expect(page.getByLabel('작업 프로젝트 메뉴')).toBeFocused();
    await page.getByLabel('작업 프로젝트 메뉴').press('ArrowUp');await expect(page.getByRole('menuitem',{name:'목록 새로고침'})).toBeFocused();
    await page.setViewportSize({width:390,height:844});await expect(page.getByRole('menu')).toHaveCount(0);await page.setViewportSize({width:1440,height:900});
    await page.getByRole('button',{name:'워크트리',exact:true}).click();await expect(page.getByRole('dialog')).toBeVisible();await page.keyboard.press('Escape');await expect(page.getByRole('dialog')).toHaveCount(0);
    await page.getByRole('button',{name:'워크트리',exact:true}).click();await page.getByLabel('워크트리 이름',{exact:true}).fill('로그인 수정');await page.getByLabel('생성 후 터미널 열기').uncheck();
    await page.screenshot({animations:'disabled',path:path.join(output,'create-without-terminal.png')});
    await page.getByRole('button',{name:'워크트리 만들기',exact:true}).click();await expect(page.getByRole('dialog')).toHaveCount(0);assert.equal(host.getState().terminals.length,1);await expect(pane(original.id)).toBeVisible();
    const login=worktree('로그인 수정');assert.ok(login.managed);
    await expect(page.locator('[data-worktree-kind=linked] .lucide-git-branch')).toBeVisible();
    await page.getByRole('button',{name:'로그인 수정 워크트리 열기'}).dblclick();await expect.poll(()=>terminals(login.id).length).toBe(1);
    const loginTerminal=terminals(login.id)[0];await expect(pane(loginTerminal.id)).toBeVisible();await expect(page.getByRole('tab',{name:/로그인 수정 ·/})).toHaveAttribute('aria-selected','true');
    await pane(loginTerminal.id).getByRole('button',{name:'탭 추가',exact:true}).click();await expect(page.getByLabel('시작 폴더',{exact:true})).toHaveValue(path.normalize(login.path));await page.getByRole('button',{name:'터미널 열기',exact:true}).click();
    await expect.poll(()=>terminals(login.id).length).toBe(2);const extra=terminals(login.id).find(t=>t.id!==loginTerminal.id)!;await expect(pane(extra.id)).toBeVisible();
    await page.locator(`#terminal-tab-${extra.id}`).dblclick();await page.getByLabel('이름',{exact:true}).fill('테스트');await page.getByRole('button',{name:'저장',exact:true}).click();
    await expect(page.getByRole('tab',{name:'로그인 수정 · 테스트'})).toBeVisible();
    await page.getByRole('button',{name:'작업 프로젝트 열기'}).click();await page.getByRole('button',{name:'로그인 수정 워크트리 열기'}).click();await expect(pane(extra.id)).toBeVisible();assert.equal(terminals(login.id).length,2);
    await page.getByRole('button',{name:'워크트리',exact:true}).click();await page.getByLabel('워크트리 이름',{exact:true}).fill('디자인 변경');await expect(page.getByLabel('생성 후 터미널 열기')).toBeChecked();await page.getByRole('button',{name:'만들고 터미널 열기'}).click();await expect(page.getByRole('dialog')).toHaveCount(0);
    const design=worktree('디자인 변경'),designTerminal=terminals(design.id)[0];await expect(pane(designTerminal.id)).toBeVisible();
    await writeFile(path.join(design.path,'design-only.txt'),'separate worktree');assert.equal(existsSync(path.join(fixture.repository,'design-only.txt')),false);assert.equal(existsSync(path.join(login.path,'design-only.txt')),false);
    await page.getByRole('button',{name:'작업 프로젝트 열기'}).click();
    const state=host.getState();await host.handle('control.acquire',{hostId:state.hostId,bootId:state.bootId,id:designTerminal.id,generation:designTerminal.generation,cols:90,rows:24},remote);
    await page.getByRole('button',{name:'디자인 변경 워크트리 열기'}).click();await expect(pane(designTerminal.id)).toBeVisible();assert.equal(host.getState().terminals.find(t=>t.id===designTerminal.id)?.controller?.connectionId,remote.id);
    assert.equal(host.getState().terminals.find(t=>t.id===original.id)?.pid,original.pid);
    await page.screenshot({animations:'disabled',path:path.join(output,'desktop.png')});
    await page.getByRole('button',{name:'로그인 수정 터미널 2개 선택'}).click();await page.getByRole('dialog').getByRole('button',{name:/로그인 수정 · 테스트/}).click();await expect(pane(extra.id)).toBeVisible();
    let releaseOpen!:()=>void;delayedOpen={entered:false,release:new Promise<void>(resolve=>releaseOpen=resolve)};
    await page.getByRole('button',{name:'디자인 변경 워크트리 열기'}).click();await expect.poll(()=>delayedOpen?.entered).toBe(true);
    await page.getByRole('tab',{name:/작업 프로젝트 ·/}).click();await expect(pane(original.id)).toBeVisible();releaseOpen();await expect(page.getByRole('button',{name:'디자인 변경 워크트리 열기'})).toBeEnabled();await expect(pane(original.id)).toBeVisible();
    await page.getByLabel('로그인 수정 워크트리 메뉴').click();await expectAnchoredMenu('로그인 수정');
    await page.screenshot({animations:'disabled',path:path.join(output,'desktop-menu.png')});
    await page.setViewportSize({width:1024,height:768});await expectAnchoredMenu('로그인 수정');
    await page.getByRole('menuitem',{name:'워크트리 삭제…',exact:true}).click();await expect(page.getByRole('menu')).toHaveCount(0);await page.getByRole('dialog').getByRole('button',{name:'워크트리 삭제',exact:true}).click();await expect(page.getByRole('dialog').getByRole('alert')).toContainText('터미널');await page.getByRole('dialog').getByRole('button',{name:'취소',exact:true}).click();
    await page.setViewportSize({width:1440,height:900});
    for(const terminal of terminals(login.id)){
      await page.getByRole('button',{name:`로그인 수정 · ${terminal.title} 탭 닫기`,exact:true}).click();await page.getByRole('dialog').getByRole('button',{name:'종료하고 닫기',exact:true}).click();await expect.poll(()=>host.getState().terminals.some(t=>t.id===terminal.id)).toBe(false);
    }
    await expect(page.getByRole('button',{name:'로그인 수정 워크트리 열기'})).toBeVisible();await page.getByRole('button',{name:'로그인 수정 워크트리 열기'}).click();await expect.poll(()=>terminals(login.id).length).toBe(1);assert.notEqual(terminals(login.id)[0].id,loginTerminal.id);
    await page.reload();await expect(page.getByRole('button',{name:'로그인 수정 워크트리 열기'})).toBeVisible();assert.equal(terminals(login.id).length,1);
    await page.getByRole('button',{name:'워크트리',exact:true}).click();await page.getByLabel('워크트리 이름',{exact:true}).fill('응답 복구');await page.getByLabel('생성 후 터미널 열기').uncheck();
    await page.getByText('고급 설정',{exact:true}).click();await page.getByLabel('기존 브랜치 연결').check();await expect(page.getByLabel('연결할 브랜치').locator('option[value="main"]')).toHaveJSProperty('disabled',true);await page.getByLabel('기존 브랜치 연결').uncheck();
    loseCreateResponse=true;await page.getByRole('button',{name:'워크트리 만들기',exact:true}).click();await expect(page.getByRole('alert')).toContainText('응답 유실');await expect(page.getByLabel('워크트리 이름',{exact:true})).toBeDisabled();
    await page.getByRole('button',{name:'결과 확인',exact:true}).click();await expect(page.getByRole('dialog')).toHaveCount(0);assert.equal(host.getState().worktrees!.filter(w=>w.name==='응답 복구').length,1);assert.equal(terminals(worktree('응답 복구').id).length,0);
    await page.setViewportSize({width:390,height:844});await page.getByRole('button',{name:'그룹 메뉴 열기'}).click();await expect(page.getByRole('button',{name:'디자인 변경 워크트리 열기'})).toBeVisible();await page.screenshot({animations:'disabled',path:path.join(output,'mobile-sidebar.png')});
    await page.getByLabel('디자인 변경 워크트리 메뉴').click();await expectAnchoredMenu('디자인 변경');await page.screenshot({animations:'disabled',path:path.join(output,'mobile-menu.png')});
    await page.keyboard.press('Escape');await expect(page.getByRole('menu')).toHaveCount(0);await expect(page.locator('.sidebar.open')).toHaveCount(1);
    await page.setViewportSize({width:320,height:480});await page.getByLabel('응답 복구 워크트리 메뉴').click();await expectAnchoredMenu('응답 복구','above');await page.screenshot({animations:'disabled',path:path.join(output,'mobile-menu-above.png')});
    await page.locator('.group-list').evaluate(element=>element.scrollTop=0);await expect(page.getByRole('menu')).toHaveCount(0);
    await page.setViewportSize({width:390,height:844});await page.getByLabel('디자인 변경 워크트리 메뉴').click();await expectAnchoredMenu('디자인 변경');
    await page.getByRole('button',{name:'디자인 변경 워크트리 열기'}).click();await expect(page.getByRole('menu')).toHaveCount(0);await expect(pane(designTerminal.id)).toBeVisible();await expect(page.locator('.sidebar.open')).toHaveCount(0);await page.screenshot({animations:'disabled',path:path.join(output,'mobile-terminal.png')});
    await page.setViewportSize({width:1440,height:900});
    const secondRepository=path.join(fixture.root,'backend');await mkdir(secondRepository);await git(secondRepository,'init','-q','--initial-branch=server');await writeFile(path.join(secondRepository,'README.md'),'# Backend\n');await git(secondRepository,'add','.');await git(secondRepository,'commit','-qm','fixture');
    const rightmostId=leafIds(host.getState().groups[0].layout).at(-1)!;
    await page.locator(`#terminal-tab-${rightmostId}`).click();await pane(rightmostId).locator('.xterm-screen').click({position:{x:30,y:40}});await expect(pane(rightmostId).locator('.control-chip.controlled')).toBeVisible();
    await page.keyboard.type(`cd /d "${secondRepository}"`);await page.keyboard.press('Enter');
    await expect.poll(()=>host.getState().terminals.find(item=>item.id===rightmostId)?.currentCwd).toBe(secondRepository);
    await page.locator(`#terminal-tab-${original.id}`).click();await pane(original.id).getByRole('button',{name:'탭 추가',exact:true}).click();
    await expect(page.getByLabel('시작 폴더',{exact:true})).toHaveValue(secondRepository);
    await page.getByRole('button',{name:'터미널 열기',exact:true}).click();
    const backendTerminal=host.getState().terminals.at(-1)!;assert.equal(backendTerminal.cwd,secondRepository);assert.equal(backendTerminal.worktreeId,undefined);
    await pane(backendTerminal.id).getByRole('button',{name:'워크트리',exact:true}).click();
    await expect(page.getByLabel('대상 저장소')).toHaveText(secondRepository.replaceAll('\\','/'));await expect(page.getByLabel('기준 브랜치',{exact:true})).toHaveValue('server');
    await page.getByLabel('워크트리 이름',{exact:true}).fill('백엔드 수정');await page.getByLabel('생성 후 터미널 열기').uncheck();await page.getByRole('button',{name:'워크트리 만들기',exact:true}).click();await expect(page.getByRole('dialog')).toHaveCount(0);
    assert.equal(host.getState().groups.length,1);assert.equal(host.getState().groups[0].repositoryIds?.length,2);assert.equal(terminals(worktree('백엔드 수정').id).length,0);
    await expect(page.getByRole('button',{name:'백엔드 수정 워크트리 열기'})).toContainText('backend');
    await page.screenshot({animations:'disabled',path:path.join(output,'multiple-repositories.png')});
    await page.setViewportSize({width:800,height:900});await pane(backendTerminal.id).getByLabel('터미널 메뉴',{exact:true}).click();
    await pane(backendTerminal.id).getByRole('button',{name:'워크트리',exact:true}).click();await expect(page.getByLabel('대상 저장소')).toHaveText(secondRepository.replaceAll('\\','/'));await page.getByRole('button',{name:'취소',exact:true}).click();
    const plainPath=path.join(fixture.root,'plain');await mkdir(plainPath);
    await page.setViewportSize({width:1440,height:900});await pane(backendTerminal.id).getByRole('button',{name:'탭 추가',exact:true}).click();await page.getByLabel('시작 폴더',{exact:true}).fill(plainPath);await page.getByRole('button',{name:'터미널 열기',exact:true}).click();
    const plainTerminal=host.getState().terminals.at(-1)!;await expect(pane(plainTerminal.id).getByRole('button',{name:'워크트리',exact:true})).toBeDisabled();await expect(pane(plainTerminal.id).getByRole('button',{name:'워크트리',exact:true})).toHaveAttribute('title',/Git 저장소가 아닙니다/);
    const plainRow=page.locator(`[data-sidebar-terminal-id="${plainTerminal.id}"]`),plainButton=plainRow.locator('.worktree-main');
    await expect(plainButton).toBeVisible();await expect(plainRow.locator('small')).toHaveText('plain');await expect(plainButton).toHaveAttribute('title',new RegExp('plain'));
    const beforeSelection=host.getState(),sessions=beforeSelection.terminals.map(({id,pid,generation})=>({id,pid,generation}));
    await plainRow.getByRole('button',{name:`${plainTerminal.title} 터미널 메뉴`,exact:true}).click();
    await page.getByRole('menuitem',{name:'이름 변경',exact:true}).click();await expect(page.getByRole('dialog').getByLabel('이름',{exact:true})).toHaveValue(plainTerminal.title);
    await page.getByRole('dialog').getByLabel('이름',{exact:true}).fill('메모 작업');await page.getByRole('dialog').getByRole('button',{name:'저장',exact:true}).click();
    await expect(page.getByRole('dialog')).toHaveCount(0);await expect(plainRow.locator('strong')).toHaveText('메모 작업');await expect(page.locator(`#terminal-tab-${plainTerminal.id}`)).toHaveAttribute('aria-label','메모 작업');
    await expect.poll(()=>host.getState().terminals.find(terminal=>terminal.id===plainTerminal.id)!.title).toBe('메모 작업');
    assert.equal(host.getState().terminals.find(terminal=>terminal.id===plainTerminal.id)!.cwd,plainPath);await expect(plainRow.locator('small')).toHaveText('plain');
    await page.reload();await expect(plainRow.locator('strong')).toHaveText('메모 작업');await expect(page.locator(`#terminal-tab-${plainTerminal.id}`)).toHaveAttribute('aria-label','메모 작업');
    const linkedCount=(await page.locator('.worktree-count').allTextContents()).reduce((sum,value)=>sum+Number(value.trim()),0);
    assert.equal(linkedCount+await page.locator('[data-sidebar-terminal-id]').count(),leafIds(beforeSelection.groups[0].layout).length,'every terminal in the group count is reachable from the sidebar');
    await page.getByRole('button',{name:'작업 프로젝트 열기'}).click();await expect(pane(plainTerminal.id)).toBeHidden();
    await plainButton.click();await expect(pane(plainTerminal.id)).toBeVisible();await expect(plainButton).toHaveAttribute('aria-current','true');
    await page.setViewportSize({width:390,height:844});await page.getByRole('button',{name:'그룹 메뉴 열기'}).click();
    await plainRow.getByRole('button',{name:'메모 작업 터미널 메뉴',exact:true}).click();await page.getByRole('menuitem',{name:'이름 변경',exact:true}).click();
    await page.getByRole('dialog').getByLabel('이름',{exact:true}).fill('취소할 이름');await page.getByRole('dialog').getByRole('button',{name:'취소',exact:true}).click();await expect(plainRow.locator('strong')).toHaveText('메모 작업');
    await expect(plainButton).toBeVisible();await plainButton.click();await expect(pane(plainTerminal.id)).toBeVisible();await expect(page.locator('.sidebar.open')).toHaveCount(0);
    assert.deepEqual(host.getState().terminals.map(({id,pid,generation})=>({id,pid,generation})),sessions);
    assert.deepEqual(host.getState().groups[0].layout,beforeSelection.groups[0].layout);
    await page.setViewportSize({width:1440,height:900});await page.screenshot({animations:'disabled',path:path.join(output,'mixed-terminals-sidebar.png')});
    await git(plainPath,'init','-q','--initial-branch=main');await writeFile(path.join(plainPath,'README.md'),'# Newly initialized\n');await git(plainPath,'add','.');await git(plainPath,'commit','-qm','fixture');
    // Retry after the hover throttle, without changing this terminal's cwd.
    await expect.poll(async()=>{await page.mouse.move(400,200);await pane(plainTerminal.id).locator('.pane-toolbar').hover();return pane(plainTerminal.id).getByRole('button',{name:'워크트리',exact:true}).isEnabled();},{timeout:15000}).toBe(true);
    const newPanes:string[]=[];
    measureReads=true;maxReads=activeReads;
    for(let index=0;index<5;index++)newPanes.push((await host.handle('terminals.create',{groupId:group.id,profileId:'cmd',cwd:secondRepository,splitTarget:plainTerminal.id,axis:index%2?'horizontal':'vertical'},ctx)).id);
    for(const id of newPanes)await expect(pane(id).locator('.pane-toolbar button').filter({hasText:'워크트리'})).toBeEnabled({timeout:20000});
    assert.equal(maxReads,1,'visible panes and sidebar refreshes share bounded, serial repository inspection');
    assert.deepEqual(errors,[]);
  }catch(error){await page.screenshot({animations:'disabled',path:path.join(output,'failure.png')}).catch(()=>{});throw error;}
});
